### ISSUE TITLE
Number of results and video url filtering

### ISSUE THREAD

**Issue by TobiasCunnen** [Signbank/sign-app#1]
When requesting a list of videos with results the signs without a video are filtered out after the number of results are is called.
This can lead to the situation that you get less results then intended.

Two possible fixes the first is:

In the query for all the glosses check if Glossvideo is present in the database.

Number two:

If the signs without a video are filtered out check if there are more signs then the number of results and add those to the list.

**Comment by vanlummelhuizen** [comment]
If I understand you correctly, I think you should only query for glosses that have a Glossvideo present, both for the count-query as for the query/queries that gives you actual glosses. In Django you can reuse the same queryset for both things and then applying either `.count() ` or a slice `[` .. `]`.
